name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Remplacez par le nom de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Spécifiez la version de Node.js

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod --output-path=dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages  # La branche où déployer
          folder: dist  # Le dossier à déployer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token pour le déploiement
