name: Deploy to GitHub Pages Angular

# Ce pipeline se déclenchera à chaque fois qu'un merge est effectué sur la branche 'main'
on:
  pull_request:
    branches:
      - main

# Jobs à exécuter pour le déploiement
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Installer Node.js 18.x pour exécuter Angular CLI
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Utiliser Node.js 18.x (compatible avec Angular CLI)

      # Étape 3 : Installer les dépendances Angular
      - name: Install dependencies
        run: npm ci

      # Étape 4 : Construire l'application Angular
      - name: Build Angular app
        run: npm run build -- --output-path=dist --base-href=/AngularHW/

      # Étape 5 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
